[build]
functions = "./functions"

[[redirects]]
from = "dummy/youtube/v3/*"
to = "/.netlify/functions/dummy/:splat"
status = 200
force = true

[[redirects]]
from = "/photos/random/*"
to = "/.netlify/functions/splash/:splat"
status = 200
force = true
